FROM golang:1.24 AS build

WORKDIR /graphql

COPY go.mod go.sum ./
COPY . .

RUN go build -tags lambda.norpc -o main ./cmd/graphql/main.go
FROM public.ecr.aws/lambda/provided:al2023

COPY --from=build /graphql/main ./main

ENTRYPOINT [ "./main" ]
