services:
  graphql:
    container_name: go_graphql_nosql_graphql
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - .env:/app/.env
    working_dir: /app
    command: sh -c 'go mod tidy && air'

  dynamodb:
    container_name: go_graphql_nosql_dynamodb
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb_admin:
    container_name: go_graphql_nosql_dynamodb_admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=go_graphql_nosql_dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
