service: staggered-scheduler

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/go-graphql-users"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/go-graphql-users"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  handler:
    handler: bin/handler
    events:
      - http:
          path: /graphql
          method: POST

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
