service: staggered-scheduler

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  stage: prod
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/go-graphql-users"

package:
  patterns:
    - "!./**"
    - "./bin/**"

functions:
  handler:
    handler: bin/handler
    events:
      - http:
          path: /graphql
          method: POST
    environment:
      FRONTEND_HOST: ${FRONTEND_HOST}
      GRAPHQL_SERVER_PORT: ${GRAPHQL_SERVER_PORT}
      GRAPHQL_SERVER_HOST: ${GRAPHQL_SERVER_HOST}
      DOMAIN: ${DOMAIN}
      AWS_REGION: ${AWS_REGION}
      DYNAMO_ENDPOINT: ${DYNAMO_ENDPOINT}
      MIGRATION_ENDPOINT: ${MIGRATION_ENDPOINT}
      # Lambdaで予約されている環境変数のため、コメントアウト
      # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
