// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	DueDateTime string `json:"dueDateTime"`
	UserID      string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
